services:
  - type: web
    name: chatbot
    runtime:python
    envVars:
      - key: PYTHON_VERSION
        value:3.11.9
    region: fra
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot.py
    ports:
      - port: 10000
        protocol: tcp
