services:
  - type: web
    name: Trip_AIbot   # 自定义服务名称
    runtime: python       # 指定 Python 环境
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot.py --port=$PORT --host=0.0.0.0
    envVars:
      - key: PORT
        value: 8080       # 与 app.py 监听的端口一致
    plan: free  