services:
  - type: web
    name: chatbot
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn chatbot:flask_app --worker-class gevent --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7389327487:AAEEnsk1JMj8fan1bUFSPV30nQ4_gtfBuxA