services:
  - type: workr
    name: chatbot
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python chatbot.py
    envVars:
      - key: PORT
        value: 10000